name: Sync README to Docker Hub

on:
  push:
    branches:
      - master
    paths:
      - README.md

jobs:
  sync_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geldata/action-sync-docker-hub-readme@v1
        with:
          docker_hub_username: ${{ secrets.DOCKER_USERNAME }}
          docker_hub_password: ${{ secrets.DOCKER_PASSWORD }}
          docker_hub_repository: geldata/gel
